name: HTML Validation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  html-validator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Validate HTML
        uses: w3c/html-validator-action@v2.0.3  # Usar una versión estable
        with:
          files: index.html
          format: text  # Puedes cambiar a 'json' si prefieres un formato JSON

      - name: Upload validation result as artifact
        uses: actions/upload-artifact@v2
        with:
          name: html-validation-result
          path: html-validation.txt
          